name: Deploy Infrastructure

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create SSH Private Key
              run: |
                mkdir -p my-key
                echo "${{ secrets.PRIVATE_KEY }}" > my-key/id_rsa
                chmod 600 ssh-key/id_rsa

            - name: Set up terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.6

            - name: Terraform Init
              run: terraform init
              working-directory: Terraform

            - name: Debug Terraform Files
              run: |
                echo "Contents of main.tf:"
                cat Terraform/main.tf
                echo "Contents of variables.tf:"
                cat Terraform/variables.tf || true

            - name: Terraform Import Key Pair
              run: terraform import aws_key_pair.deployer my-key || true
              working-directory: Terraform

            - name: Get Security Group ID
              id: get_sg
              run: |
                sg_id=$(aws ec2 describe-security-groups \
                  --filters Name=group-name,Values=web_server_sg \
                  --querry 'SecurityGroup[0].GroupId --output text')
                echo "sg_id=$sg_id" >> $GITHUB_ENV
                
            - name: Terraform Import Security group
              run: terraform import aws_security_group.web_sg ${{ env.sg_id }} || true
              working-directory: Terraform

            - name: Terraform plan
              run: terraform plan -var="private_key=${{ secrets.PRIVATE_KEY}}"
              working-directory: Terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve -var="private_key=${{ secrets.PRIVATE_KEY}}"
              working-directory: Terraform

            - name: Terraform Destroy
              run: terraform destroy -auto-approve
              working-directory: Terraform

            - name: Get Instance IP
              run: |
                terraform output -raw public_ip > ../ansible/public_ip.txt
              working-directory: Terraform

            - name: Debug public IP
              run: cat ansible/public_ip.txt
            
            - name: Create Dynamic Inventory
              run: |
                ip=$(cat ansible/public_ip.txt)
                echo "[web]" > ansible/inventory.ini
                echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=ssh-key/id_rsa" >> ansible/inventory.ini

            - name: Debug Inventory
              run: cat ansible/inventory.ini
            
            - name: Run Ansible Playbook
              run: |
                ansible-playbook -i ansible/inventory.ini ansible/webserver-setup.yml
              env:
                ANSIBLE_HOST_KEY_CHECKING: "False"
