name: Deploy Infrastructure

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create SSH Private Key
              run: |
                mkdir -p ssh-key
                echo "${{ secrets.PRIVATE_KEY }}" > ssh-key/id_rsa
                chmod 600 ssh-key/id_rsa

            - name: Set up terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.5.6

            - name: Terraform Init
              run: terraform init
              working-directory: Terraform

            - name: Debug Terraform Files
              run: |
                echo "Contents of main.tf:"
                cat Terraform/main.tf
                echo "Contents of variables.tf:"
                cat Terraform/varibles.tf || true

            - name: Terraform plan
              run: terraform plan
              working-directory: Terraform

            - name: Terraform Apply
              run: terraform apply -auto-approve 
              working-directory: Terraform

            - name: Get Instance IP
              run: |
                terraform output -raw public_ip > ../ansible/public_ip.txt
              working-directory: Terraform
            
            - name: Create Dynamic Inventory
              run: |
                ip=$(cat ansible/public_ip.txt)
                echo "[web]" > ansible/inventory.ini
                echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=ssh-key/id_rsa" >> ansible/inventory.ini
            
            - name: Run Ansible Playbook
              run: |
                ansible-playbook -i ansible/inventory.ini ansible/webserver-setup.yml
              env:
                ANSIBLE_HOST_KEY_CHECKING: "False"
